apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: develop-dabin-
commonLabels:
  app: dev-nginx
  group: develop
  variant: dev

images:
  - name: nginx
    newTag: 1.18.0
bases:
  - ../develop
