apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
    - port: 8081
      targetPort: 8080
      name: web
    - port: 8082
      targetPort: 8080 # 只为演示多端口，实际都映射到容器的8080端口
      name: management
  sessionAffinity: ClientIP
