apiVersion: v1
kind: Service
metadata:
  name: headless-demo
spec:
  selector:
    name: headless-demo
  ports:
    - port: 1234
      targetPort: 1234
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      name: headless-demo
  template:
    metadata:
      labels:
        name: headless-demo
    spec:
      containers:
        - name: headless-demo
          image: busybox
          command:
            - "sleep"
            - "3600"
          imagePullPolicy: IfNotPresent
