apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc
spec:
  accessModes:
    - ReadWriteMany
  # 利用NFS的storageclass
  storageClassName: nfs-storageclass
  resources:
    requests:
      storage: 1Mi
