apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment-pvc-nfs
spec:
  replicas: 2
  selector:
    matchLabels:
      name: busybox-deployment
  template:
    metadata:
      labels:
        name: busybox-deployment
    spec:
      serviceAccount: nfs-provisioner
      containers:
        - image: busybox:1.0
          command:
            - sh
            - -c
            - "while true; do date > /mnt/index.html; hostname >> /mnt/index.html; sleep $(($RANDOM % 5 + 5)); done"
          imagePullPolicy: IfNotPresent
          name: busybox
          # busybox-pvc挂载到mnt目录
          volumeMounts:
            - name: nfs
              mountPath: /mnt
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: busybox-pvc
