apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-container
  labels:
    name: security-context-demo-container
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
    - name: sec-ctx-vol
      emptyDir: {}
  containers:
    - name: security-context-demo-container
      image: busybox:1.0
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      command:
        - "sleep"
        - "3600"
      volumeMounts:
        - mountPath: /data/demo
          name: sec-ctx-vol
      securityContext:
        runAsUser: 2000
        allowPrivilegeEscalation: false
