apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-example
  labels:
    name: secret-pod-example
spec:
  containers:
    - name: secret-pod-example
      image: busybox:1.0
      # command:
      #   - "sleep"
      #   - "3600"
      volumeMounts:
        - mountPath: "/etc/foo"
          name: "foo"
  volumes:
    - name: foo
      secret:
        secretName: mysecret
