apiVersion: v1
kind: Pod
metadata:
  name: cm-test-app
spec:
  containers:
    - name: cm-test-app
      image: busybox
      command:
        - "/bin/sh"
        - "-c"
        - "env"
      envFrom:
        - configMapRef:
            name: cm-appvars
  restartPolicy: Never
