apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod-container-vars
spec:
  containers:
    - name: test-contianer
      image: busybox
      command:
        - "/bin/sh"
        - "-c"
        - "env"
      resources:
        requests:
          memory: "32Mi"
          cpu: "125m"
        limits:
          memory: "32Mi"
          cpu: "125m"
      env:
        - name: MY_CPU_REQUESTS
          valueFrom:
            resourceFieldRef:
              containerName: test-contianer
              resource: requests.cpu
        - name: MY_MEMORY_LIMITS
          valueFrom:
            resourceFieldRef:
              containerName: test-contianer
              resource: limits.memory
  restartPolicy: Never
