apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-app
spec:
  containers:
    - name: dapi-test-app
      image: busybox
      command:
        - "/bin/sh"
        - "-c"
        - "env"
      env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
  restartPolicy: Never
