apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod-exec
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - /bin/sh
        - -c
        - echo ok > tmp/health; sleep 10; rm -rf /tmp/health; sleep 600
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/health
        initialDelaySeconds: 5
        timeoutSeconds: 1
      imagePullPolicy: IfNotPresent
