apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod-httpget
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /_status/healthz
          port: 80
        initialDelaySeconds: 5
        timeoutSeconds: 1
      imagePullPolicy: IfNotPresent
