apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod-tcpsocket
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 5
        timeoutSeconds: 1
