apiVersion: v1
kind: Pod
metadata:
  name: pod-wtih-init-container
  labels:
    name: pod-wtih-init-container
spec:
  # 初始化容器
  initContainers:
    - name: install
      image: busybox
      command:
        - wget
        - "-O"
        - "/workdir/index.html"
        - http://www.baidu.com
      volumeMounts:
        - mountPath: /workdir
          name: workdir
  # 应用容器
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: workdir
      imagePullPolicy: IfNotPresent
  # PV
  volumes:
    - name: workdir
      emptyDir: {}
