apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
  replicas: 1 # 确保集群上只有一个Pod实例
  selector: # Pod选择器，即监控和管理拥有这些标签的Pod实例
    name: redis-master
  template: # 根据此模板来生成Pod实例
    metadata:
      labels:
        name: redis-master # Pod的标签，须和Service的Selector匹配
    spec:
      containers:
        - name: master
          image: kubeguide/redis-master
          ports:
            - containerPort: 6379
          imagePullPolicy: IfNotPresent
      nodeSelector:
        zone: north
