apiVersion: v1
kind: LimitRange
metadata:
  name: limitstest
spec:
  limits:
    - type: Pod
      max:
        cpu: "4"
        memory: 2Gi
      min:
        cpu: "200m"
        memory: 6Mi
      maxLimitRequestRatio:
        cpu: "3"
        memory: "2"
      # default:
      #   cpu: 300m
      #   memory: 200Mi
    - type: Container
      max:
        cpu: "2"
        memory: 1Gi
      min:
        cpu: 100m
        memory: 3Mi
      default:
        cpu: 200m
        memory: 400Mi
      defaultRequest:
        cpu: 100m
        memory: 200Mi
      maxLimitRequestRatio:
        cpu: "5"
        memory: "4"
